# Generated by Django 5.1.6 on 2025-03-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='embedded_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
