# Generated by Django 5.1.6 on 2025-03-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_job_embedded_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='embedded_details',
        ),
    ]
