# Generated by Django 5.1.6 on 2025-02-28 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('sections', models.JSONField(blank=True, default=dict, null=True)),
                ('parsed_text', models.TextField()),
                ('match_percentage', models.FloatField(default=0.0)),
                ('ai_comment', models.TextField(blank=True, null=True)),
                ('interview_questions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='account.job')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='account.resume')),
            ],
        ),
    ]
